export const ADD_PROJECT = 'ADD_PROJECT'
export const PUT_PROJECT = 'PUT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DEFINE_PROJECTS = 'DEFINE_PROJECTS'

export const NOTIFICATION = 'NOTIFICATION'